project_id = "ytqqkadcaihfzichukvw"

[functions.send-contact-email]
verify_jwt = false

[functions.school-chat]
verify_jwt = false

[functions.notify-admin-signup]
verify_jwt = false

[functions.generate-worksheet]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.elevenlabs-stt]
verify_jwt = false

[functions.spoken-english-feedback]
verify_jwt = false

